version: '3.4'

services:
  backend:
    build: ./back/
    container_name: backend
    ports:
    - "4003:4003"
    depends_on:
    - mongo-database
  mongo-database:
    image: mongo:4.0.10
    container_name: mongo-database
    ports:
        - "27017:27017"